name: CI/CD Kawabanga

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Execute script
        run: make build

      - name: Debug directory
        run: ls -al

      - name: Read new Output
        run: make result
