name: CI/CD Kawabanga

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting with Black
        uses: datadog/action-py-black-formatter@v2.1
        with:
          check_mode: "true"
  build:
    needs: black

    runs-on: ubuntu-latest

    steps:
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Execute script
        run: make build

      - name: Read new Output
        run: make result
